services:
  litl:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3030:3000
    networks:
      - caddy_compare-your-life-network
networks:
  caddy_compare-your-life-network: